YUI.add('module-tests', function(Y) {

    var suite = new Y.Test.Suite('gallery-itsapanel');

/*

todo:

test1: is a form generated when editable elements, but no formtag in the template nor in the container

test2: is a form NOT generated when editable elements and a formtag in the template available but not in the container

test3: is a form NOT generated when editable elements and the container is a formtag

*/
    suite.add(new Y.Test.Case({
        name: 'Memory Tests',
        setUp : function () {
            this.panel1 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: 'some message',
                visible: true,
                dragable: true
            });
            this.panel2 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: 'some message',
                visible: true,
                dragable: true
            });
            this.panel3 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: 'some message',
                visible: true,
                dragable: true
            });
        },
        tearDown : function () {
            this.panel1.destroy();
            this.panel2.destroy();
            this.panel3.destroy();
        },
        'test GC': function() {
            this.panel1.render();
            this.panel2.render();
            // no rendering panel3, because that leads to different destruction
            Y.Assert.pass();
        }
    }));

    suite.add(new Y.Test.Case({
        name: 'Memory Tests with model',
        setUp : function () {
            this.view1 = new Y.View();
            this.view2 = new Y.View();
            this.view3 = new Y.View();
            this.view1.render = function() {
                var container = this.get('container');
                container.setHTML('You are seeing <b>Y.ITSAPanel</b> with its content generated by a Y.View instance.');
            };
            this.view2.render = function() {
                var container = this.get('container');
                container.setHTML('You are seeing <b>Y.ITSAPanel</b> with its content generated by a Y.View instance.');
            };
            this.view3.render = function() {
                var container = this.get('container');
                container.setHTML('You are seeing <b>Y.ITSAPanel</b> with its content generated by a Y.View instance.');
            };
            this.panel1 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: this.view1,
                visible: true,
                dragable: true
            });
            this.panel2 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: this.view2,
                visible: true,
                dragable: true
            });
            this.panel3 = new Y.ITSAPanel({
                centered: true,
                title: 'Information',
                footer: 'Copyright (c) 2013 <a href="http://itsasbreuk.nl">Its Asbreuk</a>.',
                body: this.view3,
                visible: true,
                dragable: true
            });
        },
        tearDown : function () {
            this.panel1.destroy();
            this.panel2.destroy();
            this.panel3.destroy();
            this.view1.destroy();
            this.view2.destroy();
            this.view3.destroy();
        },
        'test GC2': function() {
            this.panel1.render();
            this.panel2.render();
            // no rendering panel3, because that leads to different destruction
            Y.Assert.pass();
        }
    }));

    Y.Test.Runner.add(suite);


},'', { requires: [ 'test', 'view', 'gallery-itsapanel'] });
